# Generated by Django 4.1.6 on 2023-02-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
    ]
