# Generated by Django 4.1.6 on 2023-02-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
